### ISSUE TITLE
optional Array/Set extension to allow casting all members of a collection

### ISSUE THREAD

**Issue by krisleech** [saturnflyer/casting#19]
What do you think of the idea of adding an optionally required extension for Array and Set to allow this:

``` ruby
[thing_1, thing_2 ... ].cast_members_as(ThingPresenter)
```

It would return a new array where each member has been cast as a `ThingPresenter`.

Out of scope of casting or a consideration?

**Comment by gregory** [comment]
ping :)

**Comment by krisleech** [comment]
@gregory I didn't currently do any further work on this. Would you like to take this forward or shall I close this issue for now?

**Comment by saturnflyer** [comment]
I'd love to have more feedback on this @gregory

**Comment by gregory** [comment]
No need for now, i was just wondering since this is the first thing that came to my mind when i saw casting :)
Using DelegateClass for now. might consider to use casting pretty soon. i'll then get back to you guys.
@krisleech feel free to close, we could still reopen in the futur.

**Comment by saturnflyer** [comment]
It's been a long time but I think this might be solved by https://github.com/saturnflyer/casting/blob/297699ee9f58fa4a4c00fc89e442b700d9459e55/lib/casting/enum.rb

Closing but please reopen if that doesn't do it.
